### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nickalleyne**
Fixed the symlink in step 3.

### CODE REVIEW

**Comment by nickalleyne** [comment]
Hey there, I fixed the symlink.  You made an adjustment a couple weeks ago, but I think this is the correct link.

**Comment by skyslasher** [comment]
There are two errors in the provided commands in the Setup section that nearly drove me nuts :-) Here are the corrected sections:
3. Symlink container proxy boot script
`$ ln -sf /mnt/data/proxy/on_boot.d/30-proxy.sh /mnt/data/on_boot.d/.`
5. Register the container with podman
`$ podman run -d --systemd=false --network proxy --name proxy -v "/mnt/data/proxy/Caddyfile:/etc/caddy/Caddyfile" xpherism/udm-proxy`

**Comment by nickalleyne** [comment]
Hi @xpherism just checking in to see if these make sense and/or you can merge this?

Thanks,

**Comment by xpherism** [comment]
> Hi @xpherism just checking in to see if these make sense and/or you can merge this?
> 
> 
> 
> Thanks,

Sorry for the late response :-/ PR looks fine, thank you :-)

**Pull request merged**
